<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'af3cc937b8a54e5b4209c82d6cfe8889' => $vendorDir . '/param-processor/param-processor/DefaultConfig.php',
    'ad155f8f1cf0d418fe49e248db8c661b' => $vendorDir . '/react/promise/src/functions_include.php',
    '94e265ce14c952a920a4ea5f7e8e9baa' => $vendorDir . '/mediawiki/parser-hooks/ParserHooks.php',
    '5a04c63399fef01344b45823e301d04d' => $vendorDir . '/onoi/shared-resources/Resources.php',
    'a4a119a56e50fbb293281d9a48007e0e' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    '8592c7b0947d8a0965a9e8c3d16f9c24' => $vendorDir . '/elasticsearch/elasticsearch/src/autoload.php',
    'cd9b6b6b76aed1304a64986142337d3a' => $baseDir . '/extensions/SemanticMediaWiki/SemanticMediaWiki.php',
    'eccc0347283a01e62f5536bcf76b6e62' => $vendorDir . '/wikimedia/at-ease/src/Wikimedia/Functions.php',
    '7b11c4dc42b3b3023073cb14e519683c' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'a0edc8309cc5e1d60e3047b5df6b7052' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    'e69f7f6ee287b969198c3c9d6777bd38' => $vendorDir . '/symfony/polyfill-intl-normalizer/bootstrap.php',
    '25072dd6e2470089de65ae7bf11d3109' => $vendorDir . '/symfony/polyfill-php72/bootstrap.php',
    'c3f7f0e81464740a933532e81fa26cc7' => $vendorDir . '/wikimedia/base-convert/src/Functions.php',
    'c964ee0ededf28c96ebd9db5099ef910' => $vendorDir . '/guzzlehttp/promises/src/functions_include.php',
    'c3ae67574219cc56cab6c30ef8877b85' => $baseDir . '/extensions/Validator/Validator.php',
    'f598d06aa772fa33d905e87be6398fb1' => $vendorDir . '/symfony/polyfill-intl-idn/bootstrap.php',
    'c50606d667a3fde2b80a955639479d3d' => $vendorDir . '/wikimedia/timestamp/src/defines.php',
    '37a3dc5111fe8f707ab4c132ef1dbc62' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    '5cee90b14a8622b5d28c28559972ca28' => $baseDir . '/extensions/Maps/Maps_Settings.php',
    'd18fa3b1dccd02b483afde268abd780d' => $baseDir . '/extensions/SemanticCite/SemanticCite.php',
    '3324dfbc75ea60346550e520d749543d' => $baseDir . '/extensions/SemanticCompoundQueries/SemanticCompoundQueries.php',
    '49b46b7a2828914e66c76de75c8414c0' => $baseDir . '/extensions/SemanticExtraSpecialProperties/SemanticExtraSpecialProperties.php',
    '43b3c7644dd913f46db744c4ac998fef' => $baseDir . '/extensions/SemanticResultFormats/SemanticResultFormats.php',
    'f2252e86055d59cbb0c41168be6e62e9' => $baseDir . '/extensions/SemanticScribunto/SemanticScribunto.php',
    '4d945db823e5f6ca6dd83ad1f5fbcc43' => $vendorDir . '/wikimedia/relpath/src/RelPath/RelPath.php',
    '6513700b70192b7dfd0e5e9fc8082cf3' => $vendorDir . '/wikimedia/relpath/src/Wikimedia/RelPath.php',
);
