<?php return array(
    'root' => array(
        'name' => 'mediawiki/core',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '655a20712aed4af7f656111a90aefc665b80b836',
        'type' => 'mediawiki-core',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'reference' => '647490bbcaf7fc4891c58f47b825eb99d19c377a',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cssjanus/cssjanus' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'reference' => '93db9fb39c2f9bcf287715ae254c088b14a77799',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cssjanus/cssjanus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/common' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '9f5e6216ec66ac8f2281351b110bad0eded43e65',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/data-values' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '1084142918095dfedf9b6cc0de0755f8c4628264',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/data-values',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/geo' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'reference' => '1dd742dabb63e211862486259b2cbe0274211bf9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/geo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/interfaces' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '244d078954bc05edf8f8c6b088e848289171c3a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/interfaces',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/validators' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '83dbac2c5e9442e8fa2119c8b941ecb88156abe8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/validators',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v6.8.2',
            'version' => '6.8.2.0',
            'reference' => '619c78266999c6e431df9ca0f844e8f656ac145b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezimuel/guzzlestreams' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'b4b5a025dfee70d6cd34c780e07330eb93d5b997',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/guzzlestreams',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezimuel/ringphp' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '7887fc8488013065f72f977dcb281994f5fde9f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/ringphp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.8',
            'version' => '6.5.8.0',
            'reference' => 'a52f0440530b54fa079ce76e8c5d196a42cad981',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'reference' => 'e4490cabc77465aaee90b20cfc9a770f8c04be6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.2',
            ),
        ),
        'jeroen-de-dauw/simple-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jeroen/file-fetcher' => array(
            'pretty_version' => '6.1.0',
            'version' => '6.1.0.0',
            'reference' => 'd38fb0587b52b28bd24fda599f2da69ac8530453',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/file-fetcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeroen/file-fetcher-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '048ca2f966edcb38989332d13543185e864200ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/file-fetcher-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeroen/simple-cache' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '159a72cf2ba7b7506495914d294d9e423700bd54',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeroen/simple-geocoder' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '1a9e6a6b8318d712363b53b1715aee5ce266e6b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/simple-geocoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jmikola/geojson' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '3699d2be8961f2c2f20b33041b6f0608d2cf4332',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jmikola/geojson',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.12',
            'version' => '5.2.12.0',
            'reference' => 'ad87d5a5ca981228e0e205c2bc7dfb8e24559b60',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'liuggio/statsd-php-client' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'reference' => 'c42e6d6687b7b2d7683186ec7f4f03351cc3dbca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../liuggio/statsd-php-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '655a20712aed4af7f656111a90aefc665b80b836',
            'type' => 'mediawiki-core',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/data-values' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/maps' => array(
            'pretty_version' => '7.20.1',
            'version' => '7.20.1.0',
            'reference' => 'd3ebb2c437678dd8477910274cdbfe6b030666f7',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/Maps',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/mediawiki' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.35.10',
            ),
        ),
        'mediawiki/mermaid' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'fd792683fef3c84a7cdd56f8f474c4da0dd630f2',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/Mermaid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/parser-hooks' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '45660efef737bcf33abbbb12c1ddb049c4e713fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/parser-hooks',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-cite' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '01dc68a453e1d85146742bf7b89623e761056728',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticCite',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-compound-queries' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'eeb514393fdf2e80ae7084839d8803ee32ae3da4',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticCompoundQueries',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-extra-special-properties' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '01a45e484adf008f5edc23e3f499d92863e379f7',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticExtraSpecialProperties',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-maps' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/semantic-media-wiki' => array(
            'pretty_version' => '3.2.3',
            'version' => '3.2.3.0',
            'reference' => '5619c2db49184e862eecc72375e190de0e103df7',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticMediaWiki',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-mediawiki' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/semantic-result-formats' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'ecbf369424ae5cd59315a4dca24f50d3af70702a',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticResultFormats',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-scribunto' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1c616a4c4da443b3433000d6870bb92c184236fa',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticScribunto',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/validator' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'reference' => '944421640b3b34273b3722fbfd155550f1c7a8c6',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/Validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nicmart/tree' => array(
            'pretty_version' => 'v0.2.7',
            'version' => '0.2.7.0',
            'reference' => '0616b54bb49938e1a816141d7943db48ebf76938',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nicmart/tree',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/blob-store' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'c3e1f15214977e904fc0e91e0480175a464977ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/blob-store',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/cache' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'ecc999186aab7c8db411aedd892b2e5fe5a0b422',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/callback-container' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'cf2f4dda1b2479bc786985fdb5554af528d03e52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/callback-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/event-dispatcher' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2af64e3997fc59b6d1e1f8f77e65fd6311c37109',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/http-request' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'a7cf33bae82cffe570086fc06d6617e802c0cc74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/http-request',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/message-reporter' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'reference' => 'ead8ef8f2868ccee6881e471295ebbaf8428c96c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/message-reporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/remi' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'reference' => '48898ecd1387656f6decc5bb1e38b4ecbdde5e4a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/remi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/shared-resources' => array(
            'pretty_version' => '0.4.3',
            'version' => '0.4.3.0',
            'reference' => '322273a7462eb0c15305dde9207138f00a387080',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/shared-resources',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/tesa' => array(
            'pretty_version' => '0.1.0',
            'version' => '0.1.0.0',
            'reference' => 'c8a07ca8738cf6d644e83d10ba2cb1ef93dffa7d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/tesa',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'oojs/oojs-ui' => array(
            'pretty_version' => 'v0.39.3',
            'version' => '0.39.3.0',
            'reference' => '517e59fe02a6857c35220094b8ece47800a7344e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oojs/oojs-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'param-processor/param-processor' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '0850dc2af72d31b8f645e0f87a44ff4b68583a64',
            'type' => 'library',
            'install_path' => __DIR__ . '/../param-processor/param-processor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v1.4.1',
            'version' => '1.4.1.0',
            'reference' => '9609ed5e42ac5b221dfd9af85de005c59d418ee7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.11',
            'version' => '1.10.11.0',
            'reference' => 'd4fb9ce61201593d0f8c6db629c45e29c3409c14',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'reference' => 'ee0e156ab94b37ac7ad10623a4a62f10a2a2d421',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.13',
            'version' => '1.10.13.0',
            'reference' => 'aed862e95fd286c53cc546734868dc38ff4b5b1d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pleonasm/bloom-filter' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '4a3292c9f83a778c44271bf4e4f6be1204b87f7b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pleonasm/bloom-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '0f73288fd15629204f9d42b7055f72dacbe811fc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.9.0',
            'version' => '2.9.0.0',
            'reference' => '234f8fd1023c9158e2314fa9d7d0e6a83db42910',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.13',
            ),
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => '9ad6ce79c342fbd44df10ea95511a1b24dee5b57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serialization/serialization' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '6fa293415e2b70c30c1e673d8bcd04d27dc15e44',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serialization/serialization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'reference' => 'da3d9da2ce0026771f5fe64cb332158f1bd2bc33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '4407588e0d3f1f52efb65fbe92babe41f37fe50c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/assert' => array(
            'pretty_version' => 'v0.5.0',
            'version' => '0.5.0.0',
            'reference' => 'd8e97f15b8f3d3799899e3d56452d34511be5764',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/at-ease' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '013ac61929797839c80a111a3f1a4710d8248e7a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/at-ease',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/base-convert' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '449f0d0237cf1e0e71faec90680c88d4af6e711d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/base-convert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cdb' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => 'd49d96232f045311dc1f21bf0d7e40adf82a1f1d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cdb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cldr-plural-rule-parser' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '2b623a411b1a8efa4363e9fda9da496ab83a5d69',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cldr-plural-rule-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/common-passwords' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'reference' => 'b9db612730d427a55e28f4a9b143b87fd72173e0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/common-passwords',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/html-formatter' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '3abeb56b30f436a486735ca53f6af0ba6367e4cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/html-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-set' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'f84555041a405f0ea51c64a0c7fb5fac36e99b84',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-set',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-utils' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c505b99c0dfab12254d64a5e064bddd13cf066ad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/object-factory' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'd2e8cba4c8d98c29f6dd2f93cf19b0792dd83d42',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/object-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/parsoid' => array(
            'pretty_version' => 'v0.12.3',
            'version' => '0.12.3.0',
            'reference' => '84b1154f535c7a8c5e64d28f2646935f05efecef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/parsoid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/password-blacklist' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^0.1.4',
            ),
        ),
        'wikimedia/php-session-serializer' => array(
            'pretty_version' => 'v1.0.7',
            'version' => '1.0.7.0',
            'reference' => '9382814e701c94358ae02f3260b7ac4951385d83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/php-session-serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/purtle' => array(
            'pretty_version' => 'v1.0.7',
            'version' => '1.0.7.0',
            'reference' => '569064c065caae036cd5a685574b6f96f05cfe33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/purtle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/relpath' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '35e701ff16abf461bb8676a9d9177f86fa0b2c94',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/relpath',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/remex-html' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '7792461b0605b1fcd4bba47bf54cdc64790edb48',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/remex-html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/running-stat' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'reference' => '60eebada7cc64b7073d90e7d4bab00efaafa0ba9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/running-stat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/scoped-callback' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => '0a480d9a9772634697c77598726cf24606597bd0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/scoped-callback',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/services' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '5ef69a8a8b0d2ea115d08469bdab468f58fac820',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/textcat' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '4f13aed2b32382c9d2fe9dc8b3e3fbb26ea4a2a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/textcat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/timestamp' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => '42ce5586d2189826e28ebcf4cedc96226b6d77e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/timestamp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/utfnormal' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'ec1ec7ce9e25cd275c532afd30bb6092a7633990',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/utfnormal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wait-condition-loop' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '0321b8ca6a0f701f96e04e5e8e6d3e244ab05338',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wait-condition-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wikipeg' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => 'df47c20859c80923d08ce906c5c7412161ef052f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wikipeg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wrappedstring' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'reference' => '11b01a2286fd377cb15c2f5561e10f56d58f37a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wrappedstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/xmp-reader' => array(
            'pretty_version' => '0.8.5',
            'version' => '0.8.5.0',
            'reference' => '99e6c9397d281f3c9842f3e72588fc04ef3e6fa4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/xmp-reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/zest-css' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'reference' => 'bc3346fcf2a93f02a8a6697d98c305c14ef1869f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/zest-css',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'willdurand/geocoder' => array(
            'pretty_version' => '4.6.0',
            'version' => '4.6.0.0',
            'reference' => 'be3d9ed0fddf8c698ee079d8a07ae9520b4a49a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/geocoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zordius/lightncandy' => array(
            'pretty_version' => 'v1.2.5',
            'version' => '1.2.5.0',
            'reference' => '37aa381e0f27d411a630062070c7a5a2174c62e7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zordius/lightncandy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
